// Auto-generated by preprocess.py — do not edit manually
const ANALYTICS = {
  "kpis": {
    "total": 6607,
    "avg_score": 67.24,
    "avg_attend": 79.98,
    "avg_hours": 19.98,
    "high_risk": 1022,
    "medium_risk": 2354,
    "low_risk": 3231,
    "top_cluster": "Driven Achiever",
    "top_cluster_pct": 20.6
  },
  "clusters": [
    {
      "id": 0,
      "name": "Driven Achiever",
      "icon": "\ud83d\ude80",
      "color": "#7C3AED",
      "description": "High study hours, excellent attendance, strong motivation. These students consistently perform at the top.",
      "strategies": [
        "Offer advanced challenge projects and enrichment tasks to maintain engagement.",
        "Assign peer mentoring roles to reinforce their own learning through teaching.",
        "Provide access to competitions (Olympiads, subject fairs) and external programs.",
        "Give autonomy in project-based learning \u2014 they thrive with creative freedom.",
        "Regularly celebrate milestones to sustain intrinsic motivation long-term."
      ],
      "count": 1362,
      "avg_score": 70.03,
      "avg_hours": 20.24,
      "avg_attend": 89.83,
      "avg_tutor": 1.52,
      "avg_sleep": 6.77,
      "avg_prev": 89.33,
      "risk_high": 18
    },
    {
      "id": 1,
      "name": "Consistent Worker",
      "icon": "\ud83d\udcda",
      "color": "#0EA5E9",
      "description": "Steady attendance and moderate study hours. Reliable performers who respond well to structured learning.",
      "strategies": [
        "Use structured study plans and weekly goal-setting exercises.",
        "Introduce spaced repetition tools (flashcards, quizzes) for retention.",
        "Leverage collaborative study groups \u2014 they excel when paired with peers.",
        "Offer regular, specific feedback to help them identify precise gaps.",
        "Introduce slightly harder problems progressively to build confidence."
      ],
      "count": 1225,
      "avg_score": 68.37,
      "avg_hours": 19.67,
      "avg_attend": 89.03,
      "avg_tutor": 1.53,
      "avg_sleep": 5.9,
      "avg_prev": 64.15,
      "risk_high": 21
    },
    {
      "id": 2,
      "name": "Passive Coaster",
      "icon": "\ud83c\udf0a",
      "color": "#F59E0B",
      "description": "Average attendance and minimal study effort. These students coast without clear academic direction.",
      "strategies": [
        "Connect curriculum topics to real-world interests and career relevance.",
        "Use gamified learning (points, leaderboards) to spark engagement.",
        "Check in one-on-one to understand hidden barriers or personal challenges.",
        "Break tasks into short, achievable micro-goals to build momentum.",
        "Introduce choice in assignments to restore a sense of ownership."
      ],
      "count": 959,
      "avg_score": 68.23,
      "avg_hours": 19.79,
      "avg_attend": 88.14,
      "avg_tutor": 1.49,
      "avg_sleep": 8.72,
      "avg_prev": 66.28,
      "risk_high": 24
    },
    {
      "id": 3,
      "name": "Struggling Learner",
      "icon": "\ud83c\udd98",
      "color": "#EF4444",
      "description": "Low attendance, lower previous scores, and limited resources. High risk of falling behind without support.",
      "strategies": [
        "Assign a dedicated mentor or tutor for weekly one-on-one sessions.",
        "Coordinate with parents/guardians to reinforce learning at home.",
        "Use multi-modal teaching (videos, hands-on activities) to suit diverse styles.",
        "Ensure access to school resources: library, devices, tutoring programs.",
        "Create safe, judgment-free classroom environments to reduce anxiety."
      ],
      "count": 1458,
      "avg_score": 64.55,
      "avg_hours": 20.04,
      "avg_attend": 69.03,
      "avg_tutor": 1.5,
      "avg_sleep": 7.02,
      "avg_prev": 62.65,
      "risk_high": 515
    },
    {
      "id": 4,
      "name": "Potential Bloomer",
      "icon": "\ud83c\udf31",
      "color": "#10B981",
      "description": "High previous scores but lower current engagement or attendance. Untapped potential waiting to be unlocked.",
      "strategies": [
        "Investigate recent disengagement \u2014 personal, social, or academic triggers.",
        "Reignite curiosity with exploratory, discovery-based learning activities.",
        "Connect them with inspiring role models or alumni in their interest area.",
        "Flexible deadlines and project alternatives reduce pressure triggers.",
        "Offer leadership roles (class rep, project lead) to rebuild confidence."
      ],
      "count": 1603,
      "avg_score": 65.84,
      "avg_hours": 20.03,
      "avg_attend": 69.76,
      "avg_tutor": 1.44,
      "avg_sleep": 7.11,
      "avg_prev": 87.85,
      "risk_high": 444
    }
  ],
  "correlations": {
    "Attendance": 0.5811,
    "Hours Studied": 0.4455,
    "Previous Scores": 0.1751,
    "Access to Resources": 0.1698,
    "Parental Involvement": 0.1571,
    "Tutoring Sessions": 0.1565,
    "Peer Influence": 0.1002,
    "Family Income": 0.0946,
    "Motivation": 0.0869,
    "Teacher Quality": 0.0767,
    "Extracurricular": 0.0644,
    "Internet Access": 0.0515,
    "Physical Activity": 0.0278,
    "Sleep Hours": -0.017,
    "School Type": 0.0088
  },
  "score_dist": {
    "labels": [
      "55",
      "58",
      "61",
      "64",
      "67",
      "70",
      "73",
      "76",
      "79",
      "82",
      "85",
      "88",
      "91",
      "94",
      "97",
      "100"
    ],
    "counts": [
      1,
      27,
      288,
      1136,
      2147,
      1925,
      853,
      170,
      12,
      9,
      5,
      9,
      4,
      8,
      6,
      7
    ]
  },
  "by_school": {
    "Public": {
      "count": 4598,
      "avg_score": 67.21,
      "avg_hours": 19.98,
      "avg_attend": 79.84
    },
    "Private": {
      "count": 2009,
      "avg_score": 67.29,
      "avg_hours": 19.97,
      "avg_attend": 80.3
    }
  },
  "by_gender": {
    "Male": {
      "count": 3814,
      "avg_score": 67.23,
      "avg_hours": 19.95
    },
    "Female": {
      "count": 2793,
      "avg_score": 67.24,
      "avg_hours": 20.01
    }
  },
  "by_motiv": {
    "Low": {
      "count": 1937,
      "avg_score": 66.75,
      "avg_attend": 79.93
    },
    "Medium": {
      "count": 3351,
      "avg_score": 67.33,
      "avg_attend": 80.11
    },
    "High": {
      "count": 1319,
      "avg_score": 67.7,
      "avg_attend": 79.71
    }
  },
  "by_parent": {
    "Low": {
      "count": 1337,
      "avg_score": 66.36
    },
    "Medium": {
      "count": 3362,
      "avg_score": 67.1
    },
    "High": {
      "count": 1908,
      "avg_score": 68.09
    }
  },
  "by_income": {
    "Low": {
      "count": 2672,
      "avg_score": 66.85
    },
    "Medium": {
      "count": 2666,
      "avg_score": 67.33
    },
    "High": {
      "count": 1269,
      "avg_score": 67.84
    }
  },
  "by_resources": {
    "High": {
      "count": 1975,
      "avg_score": 68.09
    },
    "Medium": {
      "count": 3319,
      "avg_score": 67.13
    },
    "Low": {
      "count": 1313,
      "avg_score": 66.2
    }
  },
  "attend_score": [
    {
      "label": "<60%",
      "avg_score": 0.0,
      "count": 0
    },
    {
      "label": "60-70%",
      "avg_score": 64.21,
      "count": 1573
    },
    {
      "label": "70-80%",
      "avg_score": 66.28,
      "count": 1681
    },
    {
      "label": "80-90%",
      "avg_score": 68.04,
      "count": 1607
    },
    {
      "label": "90%+",
      "avg_score": 70.14,
      "count": 1746
    }
  ],
  "hour_score": [
    {
      "label": "0-10h",
      "avg_score": 63.82,
      "count": 271
    },
    {
      "label": "10-20h",
      "avg_score": 65.99,
      "count": 2808
    },
    {
      "label": "20-30h",
      "avg_score": 68.2,
      "count": 3152
    },
    {
      "label": "30-40h",
      "avg_score": 70.86,
      "count": 374
    },
    {
      "label": "40h+",
      "avg_score": 74.5,
      "count": 2
    }
  ],
  "scatter": [
    {
      "x": 77.0,
      "y": 64.0,
      "hours": 10.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 100.0,
      "y": 69.0,
      "hours": 16.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 59.0,
      "hours": 13.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 90.0,
      "y": 69.0,
      "hours": 15.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 67.0,
      "hours": 25.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 69.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 66.0,
      "hours": 28.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 100.0,
      "y": 68.0,
      "hours": 14.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 70.0,
      "y": 63.0,
      "hours": 13.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 96.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 70.0,
      "y": 70.0,
      "hours": 30.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 64.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 88.0,
      "y": 92.0,
      "hours": 1.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 89.0,
      "y": 70.0,
      "hours": 28.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 61.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 63.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 71.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 77.0,
      "y": 66.0,
      "hours": 19.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 62.0,
      "y": 60.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 94.0,
      "y": 67.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 93.0,
      "y": 72.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 66.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 94.0,
      "y": 71.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 64.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 72.0,
      "y": 67.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 87.0,
      "y": 72.0,
      "hours": 27.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 70.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 95.0,
      "y": 66.0,
      "hours": 16.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 68.0,
      "hours": 15.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 70.0,
      "hours": 21.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 66.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 74.0,
      "y": 66.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 79.0,
      "y": 67.0,
      "hours": 21.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 70.0,
      "hours": 30.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 88.0,
      "y": 71.0,
      "hours": 27.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 61.0,
      "y": 62.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 78.0,
      "y": 65.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 73.0,
      "y": 63.0,
      "hours": 24.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 88.0,
      "y": 67.0,
      "hours": 27.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 62.0,
      "y": 67.0,
      "hours": 24.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 90.0,
      "y": 70.0,
      "hours": 16.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 86.0,
      "y": 67.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 76.0,
      "y": 61.0,
      "hours": 12.0,
      "persona": 1,
      "risk": "High"
    },
    {
      "x": 84.0,
      "y": 67.0,
      "hours": 12.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 63.0,
      "y": 62.0,
      "hours": 15.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 71.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 77.0,
      "y": 68.0,
      "hours": 24.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 65.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 90.0,
      "y": 70.0,
      "hours": 9.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 64.0,
      "hours": 25.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 73.0,
      "hours": 22.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 67.0,
      "hours": 27.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 88.0,
      "y": 71.0,
      "hours": 26.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 100.0,
      "y": 71.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 71.0,
      "hours": 13.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 60.0,
      "y": 58.0,
      "hours": 4.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 95.0,
      "y": 69.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 67.0,
      "hours": 18.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 66.0,
      "hours": 20.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 82.0,
      "y": 65.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 78.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 95.0,
      "y": 69.0,
      "hours": 19.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 90.0,
      "y": 74.0,
      "hours": 32.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 100.0,
      "y": 74.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 71.0,
      "hours": 21.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 85.0,
      "y": 70.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 74.0,
      "y": 64.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 71.0,
      "hours": 19.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 66.0,
      "hours": 7.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 96.0,
      "y": 72.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 67.0,
      "hours": 21.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 65.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 84.0,
      "y": 67.0,
      "hours": 9.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 68.0,
      "y": 64.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 83.0,
      "y": 69.0,
      "hours": 22.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 65.0,
      "hours": 15.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 69.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 87.0,
      "y": 71.0,
      "hours": 25.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 65.0,
      "y": 65.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 81.0,
      "y": 68.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 66.0,
      "hours": 27.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 84.0,
      "y": 68.0,
      "hours": 19.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 84.0,
      "y": 68.0,
      "hours": 15.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 69.0,
      "y": 68.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 63.0,
      "y": 61.0,
      "hours": 10.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 90.0,
      "y": 68.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 69.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 95.0,
      "y": 69.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 67.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 70.0,
      "hours": 28.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 72.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 75.0,
      "y": 68.0,
      "hours": 15.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 66.0,
      "hours": 15.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 95.0,
      "y": 70.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 66.0,
      "hours": 13.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 76.0,
      "y": 65.0,
      "hours": 14.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 88.0,
      "y": 72.0,
      "hours": 24.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 70.0,
      "hours": 14.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 79.0,
      "y": 68.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 64.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 85.0,
      "y": 69.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 79.0,
      "y": 66.0,
      "hours": 25.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 79.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "High"
    },
    {
      "x": 89.0,
      "y": 68.0,
      "hours": 24.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 63.0,
      "hours": 19.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 77.0,
      "y": 64.0,
      "hours": 13.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 77.0,
      "y": 69.0,
      "hours": 29.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 94.0,
      "y": 68.0,
      "hours": 22.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 68.0,
      "y": 64.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 70.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 79.0,
      "y": 68.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 98.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 100.0,
      "y": 71.0,
      "hours": 14.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 70.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 65.0,
      "hours": 12.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 94.0,
      "y": 69.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 68.0,
      "hours": 24.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 69.0,
      "hours": 20.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 71.0,
      "hours": 21.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 77.0,
      "y": 67.0,
      "hours": 21.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 64.0,
      "y": 66.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 92.0,
      "y": 66.0,
      "hours": 16.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 95.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 95.0,
      "hours": 21.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 94.0,
      "y": 70.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 65.0,
      "hours": 8.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 68.0,
      "y": 70.0,
      "hours": 32.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 71.0,
      "y": 68.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 63.0,
      "y": 68.0,
      "hours": 27.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 99.0,
      "y": 68.0,
      "hours": 13.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 72.0,
      "y": 68.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 95.0,
      "y": 69.0,
      "hours": 15.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 69.0,
      "y": 64.0,
      "hours": 12.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 85.0,
      "y": 70.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 74.0,
      "hours": 26.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 96.0,
      "y": 71.0,
      "hours": 19.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 86.0,
      "y": 71.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 88.0,
      "y": 69.0,
      "hours": 23.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 71.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 68.0,
      "hours": 21.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 80.0,
      "y": 60.0,
      "hours": 12.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 62.0,
      "y": 60.0,
      "hours": 13.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 75.0,
      "y": 68.0,
      "hours": 31.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 96.0,
      "y": 70.0,
      "hours": 21.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 65.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 92.0,
      "y": 69.0,
      "hours": 19.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 66.0,
      "hours": 21.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 78.0,
      "y": 64.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 92.0,
      "y": 71.0,
      "hours": 25.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 66.0,
      "y": 63.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 72.0,
      "y": 64.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 67.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 94.0,
      "y": 69.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 68.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 89.0,
      "y": 70.0,
      "hours": 22.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 70.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 77.0,
      "y": 67.0,
      "hours": 29.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 59.0,
      "hours": 12.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 83.0,
      "y": 71.0,
      "hours": 32.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 65.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 98.0,
      "y": 68.0,
      "hours": 15.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 66.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 74.0,
      "y": 65.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 72.0,
      "y": 66.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 66.0,
      "hours": 19.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 62.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 65.0,
      "hours": 11.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 62.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 85.0,
      "y": 64.0,
      "hours": 6.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 68.0,
      "hours": 29.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 89.0,
      "y": 66.0,
      "hours": 8.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 66.0,
      "hours": 15.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 86.0,
      "y": 66.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 80.0,
      "y": 65.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 77.0,
      "y": 68.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 72.0,
      "y": 62.0,
      "hours": 16.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 100.0,
      "y": 74.0,
      "hours": 27.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 70.0,
      "hours": 24.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 72.0,
      "hours": 25.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 95.0,
      "y": 70.0,
      "hours": 14.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 85.0,
      "y": 67.0,
      "hours": 12.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 74.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 87.0,
      "y": 69.0,
      "hours": 19.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 69.0,
      "y": 66.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 96.0,
      "y": 72.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 96.0,
      "y": 70.0,
      "hours": 29.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 95.0,
      "y": 68.0,
      "hours": 6.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 68.0,
      "hours": 19.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 67.0,
      "hours": 24.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 68.0,
      "hours": 30.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 69.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 66.0,
      "hours": 27.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 66.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 72.0,
      "y": 69.0,
      "hours": 28.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 68.0,
      "hours": 26.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 88.0,
      "y": 71.0,
      "hours": 24.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 87.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 63.0,
      "y": 58.0,
      "hours": 11.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 92.0,
      "y": 75.0,
      "hours": 29.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 67.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 66.0,
      "hours": 14.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 88.0,
      "y": 71.0,
      "hours": 24.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 60.0,
      "y": 62.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 69.0,
      "y": 68.0,
      "hours": 25.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 73.0,
      "y": 64.0,
      "hours": 15.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 92.0,
      "y": 71.0,
      "hours": 22.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 88.0,
      "y": 66.0,
      "hours": 15.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 69.0,
      "hours": 27.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 64.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 68.0,
      "y": 68.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 77.0,
      "y": 67.0,
      "hours": 13.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 64.0,
      "hours": 13.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 87.0,
      "y": 67.0,
      "hours": 15.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 68.0,
      "hours": 15.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 81.0,
      "y": 70.0,
      "hours": 29.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 60.0,
      "y": 63.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 87.0,
      "y": 68.0,
      "hours": 20.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 65.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 66.0,
      "y": 68.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 94.0,
      "y": 70.0,
      "hours": 28.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 61.0,
      "y": 68.0,
      "hours": 30.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 100.0,
      "y": 76.0,
      "hours": 29.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 70.0,
      "y": 65.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 78.0,
      "y": 66.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 64.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 88.0,
      "y": 66.0,
      "hours": 19.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 69.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 69.0,
      "hours": 26.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 66.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 64.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 61.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 93.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 71.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 66.0,
      "hours": 24.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 77.0,
      "y": 66.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 94.0,
      "y": 69.0,
      "hours": 20.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 67.0,
      "hours": 30.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 87.0,
      "y": 72.0,
      "hours": 25.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 67.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 81.0,
      "y": 68.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 67.0,
      "hours": 26.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 58.0,
      "hours": 7.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 100.0,
      "y": 71.0,
      "hours": 17.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 87.0,
      "y": 68.0,
      "hours": 18.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 86.0,
      "y": 66.0,
      "hours": 9.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 67.0,
      "hours": 11.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 70.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 62.0,
      "hours": 11.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 69.0,
      "hours": 15.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 75.0,
      "hours": 30.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 64.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 62.0,
      "hours": 16.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 65.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 98.0,
      "y": 72.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 73.0,
      "hours": 30.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 94.0,
      "y": 68.0,
      "hours": 20.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 73.0,
      "hours": 29.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 65.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 68.0,
      "hours": 33.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 81.0,
      "y": 66.0,
      "hours": 24.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 89.0,
      "y": 69.0,
      "hours": 26.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 86.0,
      "y": 68.0,
      "hours": 27.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 88.0,
      "y": 70.0,
      "hours": 26.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 67.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 85.0,
      "y": 71.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 66.0,
      "hours": 9.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 97.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 95.0,
      "y": 70.0,
      "hours": 24.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 69.0,
      "y": 64.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 87.0,
      "y": 73.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 72.0,
      "hours": 22.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 79.0,
      "y": 68.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 62.0,
      "hours": 12.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 64.0,
      "y": 68.0,
      "hours": 26.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 98.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 87.0,
      "y": 74.0,
      "hours": 32.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 65.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 82.0,
      "y": 65.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 70.0,
      "hours": 21.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 74.0,
      "hours": 38.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 67.0,
      "hours": 20.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 63.0,
      "hours": 15.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 94.0,
      "y": 69.0,
      "hours": 25.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 65.0,
      "hours": 25.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 88.0,
      "y": 69.0,
      "hours": 22.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 68.0,
      "hours": 28.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 96.0,
      "y": 70.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 70.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 68.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 58.0,
      "hours": 11.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 77.0,
      "y": 66.0,
      "hours": 24.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 69.0,
      "hours": 23.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 79.0,
      "y": 64.0,
      "hours": 14.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 61.0,
      "hours": 14.0,
      "persona": 1,
      "risk": "High"
    },
    {
      "x": 85.0,
      "y": 65.0,
      "hours": 10.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 65.0,
      "hours": 22.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 60.0,
      "hours": 12.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 84.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 89.0,
      "y": 72.0,
      "hours": 36.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 76.0,
      "y": 68.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 64.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 82.0,
      "y": 68.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 64.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 78.0,
      "y": 68.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 64.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 68.0,
      "hours": 35.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 76.0,
      "y": 69.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 67.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 83.0,
      "y": 69.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 61.0,
      "y": 64.0,
      "hours": 28.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 72.0,
      "y": 63.0,
      "hours": 12.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 66.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 84.0,
      "y": 67.0,
      "hours": 23.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 63.0,
      "y": 68.0,
      "hours": 22.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 85.0,
      "y": 71.0,
      "hours": 21.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 69.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 58.0,
      "hours": 4.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 85.0,
      "y": 67.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 65.0,
      "hours": 21.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 93.0,
      "y": 71.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 67.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 65.0,
      "hours": 17.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 63.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 67.0,
      "hours": 23.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 70.0,
      "y": 64.0,
      "hours": 11.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 65.0,
      "hours": 22.0,
      "persona": 2,
      "risk": "High"
    },
    {
      "x": 67.0,
      "y": 68.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 60.0,
      "hours": 5.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 81.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 71.0,
      "hours": 16.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 71.0,
      "hours": 22.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 68.0,
      "hours": 26.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 65.0,
      "hours": 13.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 66.0,
      "hours": 10.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 64.0,
      "hours": 10.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 66.0,
      "hours": 12.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 67.0,
      "y": 71.0,
      "hours": 35.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 88.0,
      "y": 73.0,
      "hours": 30.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 61.0,
      "y": 60.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 80.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 62.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 85.0,
      "y": 67.0,
      "hours": 19.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 70.0,
      "hours": 19.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 60.0,
      "y": 63.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 90.0,
      "y": 71.0,
      "hours": 29.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 89.0,
      "y": 65.0,
      "hours": 15.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 77.0,
      "y": 70.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 75.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 96.0,
      "y": 70.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 72.0,
      "hours": 28.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 60.0,
      "hours": 9.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 76.0,
      "y": 69.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 94.0,
      "y": 69.0,
      "hours": 18.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 67.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 76.0,
      "y": 64.0,
      "hours": 11.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 65.0,
      "y": 66.0,
      "hours": 22.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 93.0,
      "y": 68.0,
      "hours": 21.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 63.0,
      "hours": 20.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 60.0,
      "y": 59.0,
      "hours": 15.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 85.0,
      "y": 70.0,
      "hours": 24.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 62.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 71.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 66.0,
      "hours": 24.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 85.0,
      "y": 66.0,
      "hours": 13.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 68.0,
      "hours": 24.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 65.0,
      "hours": 12.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 96.0,
      "y": 68.0,
      "hours": 10.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 68.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 62.0,
      "hours": 11.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 76.0,
      "y": 62.0,
      "hours": 16.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 71.0,
      "y": 67.0,
      "hours": 27.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 68.0,
      "hours": 12.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 69.0,
      "hours": 27.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 62.0,
      "y": 62.0,
      "hours": 16.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 86.0,
      "y": 71.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 70.0,
      "y": 59.0,
      "hours": 12.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 75.0,
      "y": 65.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 76.0,
      "y": 68.0,
      "hours": 27.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 66.0,
      "hours": 22.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 94.0,
      "y": 71.0,
      "hours": 21.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 61.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 93.0,
      "y": 67.0,
      "hours": 16.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 66.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 64.0,
      "hours": 11.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 68.0,
      "hours": 32.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 86.0,
      "y": 66.0,
      "hours": 26.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 98.0,
      "y": 71.0,
      "hours": 26.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 67.0,
      "hours": 16.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 68.0,
      "hours": 19.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 86.0,
      "y": 69.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 69.0,
      "hours": 24.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 65.0,
      "y": 66.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 71.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 63.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 95.0,
      "y": 69.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 74.0,
      "y": 69.0,
      "hours": 19.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 68.0,
      "y": 68.0,
      "hours": 30.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 93.0,
      "y": 70.0,
      "hours": 22.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 66.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 73.0,
      "y": 67.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 68.0,
      "y": 70.0,
      "hours": 30.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 70.0,
      "hours": 31.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 70.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 93.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 63.0,
      "hours": 16.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 65.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 64.0,
      "y": 63.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 79.0,
      "y": 68.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 99.0,
      "y": 72.0,
      "hours": 19.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 73.0,
      "hours": 26.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 65.0,
      "y": 61.0,
      "hours": 12.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 66.0,
      "y": 68.0,
      "hours": 27.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 91.0,
      "y": 71.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 74.0,
      "hours": 30.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 74.0,
      "hours": 24.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 79.0,
      "y": 65.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 68.0,
      "y": 64.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 68.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 66.0,
      "hours": 15.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 94.0,
      "y": 66.0,
      "hours": 16.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 65.0,
      "hours": 22.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 75.0,
      "y": 67.0,
      "hours": 24.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 68.0,
      "hours": 21.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 79.0,
      "y": 66.0,
      "hours": 15.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 70.0,
      "hours": 29.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 77.0,
      "y": 71.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 71.0,
      "hours": 26.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 64.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 99.0,
      "y": 74.0,
      "hours": 27.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 88.0,
      "y": 68.0,
      "hours": 15.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 84.0,
      "y": 64.0,
      "hours": 15.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 97.0,
      "y": 70.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 68.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 87.0,
      "y": 82.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 75.0,
      "y": 64.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 65.0,
      "y": 61.0,
      "hours": 8.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 89.0,
      "y": 70.0,
      "hours": 23.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 67.0,
      "hours": 19.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 80.0,
      "y": 64.0,
      "hours": 12.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 61.0,
      "hours": 5.0,
      "persona": 1,
      "risk": "High"
    },
    {
      "x": 78.0,
      "y": 70.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 69.0,
      "hours": 15.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 67.0,
      "hours": 21.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 69.0,
      "y": 65.0,
      "hours": 27.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 82.0,
      "y": 65.0,
      "hours": 11.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 72.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 69.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 66.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 73.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 99.0,
      "y": 68.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 90.0,
      "y": 70.0,
      "hours": 24.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 71.0,
      "hours": 26.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 67.0,
      "hours": 3.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 71.0,
      "hours": 25.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 68.0,
      "hours": 17.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 64.0,
      "hours": 15.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 95.0,
      "y": 69.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 87.0,
      "y": 68.0,
      "hours": 21.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 71.0,
      "hours": 27.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 71.0,
      "hours": 20.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 87.0,
      "y": 66.0,
      "hours": 20.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 100.0,
      "y": 74.0,
      "hours": 26.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 63.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 94.0,
      "y": 68.0,
      "hours": 24.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 99.0,
      "y": 70.0,
      "hours": 20.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 66.0,
      "hours": 16.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 65.0,
      "y": 62.0,
      "hours": 12.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 90.0,
      "y": 72.0,
      "hours": 24.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 83.0,
      "y": 63.0,
      "hours": 3.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 96.0,
      "y": 68.0,
      "hours": 11.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 63.0,
      "y": 69.0,
      "hours": 29.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 80.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 64.0,
      "y": 66.0,
      "hours": 19.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 79.0,
      "y": 66.0,
      "hours": 22.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 78.0,
      "y": 65.0,
      "hours": 16.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 66.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 98.0,
      "y": 68.0,
      "hours": 20.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 93.0,
      "y": 68.0,
      "hours": 24.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 82.0,
      "y": 67.0,
      "hours": 19.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 94.0,
      "y": 67.0,
      "hours": 11.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 61.0,
      "hours": 10.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 69.0,
      "y": 65.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 100.0,
      "y": 66.0,
      "hours": 11.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 77.0,
      "y": 70.0,
      "hours": 16.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 79.0,
      "y": 68.0,
      "hours": 17.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 97.0,
      "y": 75.0,
      "hours": 29.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 96.0,
      "y": 70.0,
      "hours": 21.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 65.0,
      "hours": 20.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 78.0,
      "y": 67.0,
      "hours": 23.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 66.0,
      "hours": 11.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 86.0,
      "y": 65.0,
      "hours": 8.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 68.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 71.0,
      "y": 64.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 74.0,
      "y": 63.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 75.0,
      "y": 67.0,
      "hours": 30.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 68.0,
      "y": 64.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 90.0,
      "y": 67.0,
      "hours": 8.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 69.0,
      "hours": 27.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 64.0,
      "hours": 19.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 76.0,
      "y": 66.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 63.0,
      "hours": 26.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 74.0,
      "y": 63.0,
      "hours": 14.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 74.0,
      "y": 65.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 72.0,
      "hours": 26.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 88.0,
      "y": 68.0,
      "hours": 26.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 60.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 73.0,
      "y": 62.0,
      "hours": 9.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 87.0,
      "y": 73.0,
      "hours": 28.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 69.0,
      "hours": 21.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 98.0,
      "y": 69.0,
      "hours": 18.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 74.0,
      "hours": 22.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 97.0,
      "y": 71.0,
      "hours": 15.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 66.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 60.0,
      "hours": 8.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 99.0,
      "y": 66.0,
      "hours": 12.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 91.0,
      "y": 64.0,
      "hours": 13.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 85.0,
      "y": 69.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 88.0,
      "y": 66.0,
      "hours": 7.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 66.0,
      "y": 65.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 60.0,
      "y": 65.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 67.0,
      "hours": 12.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 64.0,
      "hours": 13.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 80.0,
      "y": 66.0,
      "hours": 20.0,
      "persona": 1,
      "risk": "Medium"
    },
    {
      "x": 70.0,
      "y": 66.0,
      "hours": 21.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 66.0,
      "hours": 22.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 82.0,
      "y": 70.0,
      "hours": 16.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 65.0,
      "hours": 25.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 93.0,
      "y": 76.0,
      "hours": 29.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 66.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 97.0,
      "y": 67.0,
      "hours": 13.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 87.0,
      "y": 72.0,
      "hours": 29.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 74.0,
      "y": 65.0,
      "hours": 16.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 94.0,
      "y": 71.0,
      "hours": 28.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 79.0,
      "y": 67.0,
      "hours": 21.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 69.0,
      "y": 64.0,
      "hours": 20.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 75.0,
      "y": 65.0,
      "hours": 24.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 70.0,
      "y": 69.0,
      "hours": 33.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 91.0,
      "y": 69.0,
      "hours": 20.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 89.0,
      "y": 69.0,
      "hours": 18.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 60.0,
      "y": 60.0,
      "hours": 14.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 78.0,
      "y": 69.0,
      "hours": 24.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 75.0,
      "hours": 33.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 92.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 74.0,
      "y": 61.0,
      "hours": 9.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 85.0,
      "y": 68.0,
      "hours": 21.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 61.0,
      "y": 63.0,
      "hours": 20.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 61.0,
      "y": 60.0,
      "hours": 20.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 69.0,
      "y": 71.0,
      "hours": 26.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 99.0,
      "y": 67.0,
      "hours": 18.0,
      "persona": 2,
      "risk": "Medium"
    },
    {
      "x": 82.0,
      "y": 66.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Medium"
    },
    {
      "x": 81.0,
      "y": 69.0,
      "hours": 16.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 63.0,
      "y": 62.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 78.0,
      "y": 71.0,
      "hours": 28.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 82.0,
      "y": 69.0,
      "hours": 24.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 76.0,
      "y": 64.0,
      "hours": 20.0,
      "persona": 2,
      "risk": "High"
    },
    {
      "x": 82.0,
      "y": 69.0,
      "hours": 26.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 63.0,
      "y": 63.0,
      "hours": 17.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 67.0,
      "y": 65.0,
      "hours": 23.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 98.0,
      "y": 68.0,
      "hours": 18.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 62.0,
      "y": 65.0,
      "hours": 22.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 88.0,
      "y": 71.0,
      "hours": 21.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 62.0,
      "hours": 16.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 60.0,
      "y": 62.0,
      "hours": 18.0,
      "persona": 4,
      "risk": "High"
    },
    {
      "x": 68.0,
      "y": 64.0,
      "hours": 23.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 86.0,
      "y": 71.0,
      "hours": 23.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 68.0,
      "y": 64.0,
      "hours": 24.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 67.0,
      "y": 65.0,
      "hours": 28.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 83.0,
      "y": 68.0,
      "hours": 16.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 100.0,
      "y": 72.0,
      "hours": 23.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 78.0,
      "y": 71.0,
      "hours": 24.0,
      "persona": 4,
      "risk": "Low"
    },
    {
      "x": 84.0,
      "y": 71.0,
      "hours": 31.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 91.0,
      "y": 66.0,
      "hours": 15.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 64.0,
      "y": 61.0,
      "hours": 19.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 90.0,
      "y": 72.0,
      "hours": 25.0,
      "persona": 0,
      "risk": "Low"
    },
    {
      "x": 77.0,
      "y": 64.0,
      "hours": 17.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 98.0,
      "y": 71.0,
      "hours": 21.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 72.0,
      "y": 63.0,
      "hours": 10.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 89.0,
      "y": 67.0,
      "hours": 17.0,
      "persona": 2,
      "risk": "Low"
    },
    {
      "x": 67.0,
      "y": 61.0,
      "hours": 18.0,
      "persona": 3,
      "risk": "High"
    },
    {
      "x": 95.0,
      "y": 66.0,
      "hours": 10.0,
      "persona": 1,
      "risk": "Low"
    },
    {
      "x": 73.0,
      "y": 62.0,
      "hours": 10.0,
      "persona": 3,
      "risk": "Medium"
    },
    {
      "x": 63.0,
      "y": 63.0,
      "hours": 16.0,
      "persona": 4,
      "risk": "Medium"
    },
    {
      "x": 68.0,
      "y": 67.0,
      "hours": 28.0,
      "persona": 3,
      "risk": "Medium"
    }
  ],
  "risk_table": [
    {
      "id": 1,
      "gender": "Female",
      "school": "Private",
      "score": 58.0,
      "attend": 69.0,
      "hours": 4.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 9,
      "persona": 4,
      "internet": "No",
      "tutor": 2.0,
      "prev": 93.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 2,
      "gender": "Male",
      "school": "Public",
      "score": 60.0,
      "attend": 76.0,
      "hours": 9.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 9,
      "persona": 4,
      "internet": "No",
      "tutor": 0.0,
      "prev": 78.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 3,
      "gender": "Male",
      "school": "Private",
      "score": 60.0,
      "attend": 69.0,
      "hours": 15.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 3,
      "internet": "No",
      "tutor": 0.0,
      "prev": 53.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 4,
      "gender": "Male",
      "school": "Public",
      "score": 59.0,
      "attend": 60.0,
      "hours": 21.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 71.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 5,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 69.0,
      "hours": 5.0,
      "motiv": "Medium",
      "risk": "High",
      "risk_score": 8,
      "persona": 4,
      "internet": "No",
      "tutor": 2.0,
      "prev": 77.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 6,
      "gender": "Female",
      "school": "Private",
      "score": 61.0,
      "attend": 60.0,
      "hours": 23.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 3,
      "internet": "No",
      "tutor": 0.0,
      "prev": 56.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 7,
      "gender": "Male",
      "school": "Public",
      "score": 61.0,
      "attend": 66.0,
      "hours": 18.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 3,
      "internet": "No",
      "tutor": 1.0,
      "prev": 68.0,
      "disability": "Yes",
      "peer": "Positive"
    },
    {
      "id": 8,
      "gender": "Male",
      "school": "Private",
      "score": 57.0,
      "attend": 64.0,
      "hours": 9.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 68.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 9,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 62.0,
      "hours": 21.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 3,
      "internet": "No",
      "tutor": 1.0,
      "prev": 50.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 10,
      "gender": "Male",
      "school": "Public",
      "score": 62.0,
      "attend": 67.0,
      "hours": 20.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 4,
      "internet": "No",
      "tutor": 1.0,
      "prev": 93.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 11,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 65.0,
      "hours": 8.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 8,
      "persona": 4,
      "internet": "Yes",
      "tutor": 3.0,
      "prev": 83.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 12,
      "gender": "Female",
      "school": "Public",
      "score": 61.0,
      "attend": 64.0,
      "hours": 19.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 2.0,
      "prev": 59.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 13,
      "gender": "Male",
      "school": "Public",
      "score": 62.0,
      "attend": 64.0,
      "hours": 22.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "No",
      "tutor": 1.0,
      "prev": 98.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 14,
      "gender": "Female",
      "school": "Public",
      "score": 59.0,
      "attend": 69.0,
      "hours": 13.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 68.0,
      "disability": "Yes",
      "peer": "Positive"
    },
    {
      "id": 15,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 63.0,
      "hours": 12.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 69.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 16,
      "gender": "Male",
      "school": "Public",
      "score": 61.0,
      "attend": 62.0,
      "hours": 14.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 3.0,
      "prev": 65.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 17,
      "gender": "Female",
      "school": "Private",
      "score": 59.0,
      "attend": 60.0,
      "hours": 16.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 66.0,
      "disability": "Yes",
      "peer": "Neutral"
    },
    {
      "id": 18,
      "gender": "Male",
      "school": "Private",
      "score": 61.0,
      "attend": 67.0,
      "hours": 18.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 2.0,
      "prev": 68.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 19,
      "gender": "Male",
      "school": "Public",
      "score": 59.0,
      "attend": 64.0,
      "hours": 4.0,
      "motiv": "Medium",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 65.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 20,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 69.0,
      "hours": 18.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "No",
      "tutor": 1.0,
      "prev": 59.0,
      "disability": "No",
      "peer": "Positive"
    },
    {
      "id": 21,
      "gender": "Female",
      "school": "Public",
      "score": 61.0,
      "attend": 67.0,
      "hours": 8.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 2.0,
      "prev": 58.0,
      "disability": "No",
      "peer": "Positive"
    },
    {
      "id": 22,
      "gender": "Male",
      "school": "Public",
      "score": 55.0,
      "attend": 62.0,
      "hours": 3.0,
      "motiv": "Medium",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 67.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 23,
      "gender": "Male",
      "school": "Private",
      "score": 59.0,
      "attend": 65.0,
      "hours": 5.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 98.0,
      "disability": "No",
      "peer": "Positive"
    },
    {
      "id": 24,
      "gender": "Male",
      "school": "Public",
      "score": 58.0,
      "attend": 61.0,
      "hours": 13.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "No",
      "tutor": 1.0,
      "prev": 68.0,
      "disability": "No",
      "peer": "Neutral"
    },
    {
      "id": 25,
      "gender": "Male",
      "school": "Public",
      "score": 59.0,
      "attend": 64.0,
      "hours": 12.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "No",
      "tutor": 2.0,
      "prev": 51.0,
      "disability": "No",
      "peer": "Neutral"
    },
    {
      "id": 26,
      "gender": "Male",
      "school": "Public",
      "score": 59.0,
      "attend": 66.0,
      "hours": 16.0,
      "motiv": "Medium",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 52.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 27,
      "gender": "Female",
      "school": "Public",
      "score": 61.0,
      "attend": 61.0,
      "hours": 17.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 2.0,
      "prev": 58.0,
      "disability": "Yes",
      "peer": "Positive"
    },
    {
      "id": 28,
      "gender": "Female",
      "school": "Public",
      "score": 65.0,
      "attend": 64.0,
      "hours": 23.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 3.0,
      "prev": 80.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 29,
      "gender": "Male",
      "school": "Public",
      "score": 61.0,
      "attend": 69.0,
      "hours": 17.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 70.0,
      "disability": "Yes",
      "peer": "Neutral"
    },
    {
      "id": 30,
      "gender": "Male",
      "school": "Public",
      "score": 61.0,
      "attend": 64.0,
      "hours": 14.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 62.0,
      "disability": "Yes",
      "peer": "Positive"
    },
    {
      "id": 31,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 61.0,
      "hours": 16.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 53.0,
      "disability": "Yes",
      "peer": "Positive"
    },
    {
      "id": 32,
      "gender": "Female",
      "school": "Public",
      "score": 61.0,
      "attend": 68.0,
      "hours": 11.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 3.0,
      "prev": 91.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 33,
      "gender": "Male",
      "school": "Public",
      "score": 59.0,
      "attend": 60.0,
      "hours": 10.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "No",
      "tutor": 3.0,
      "prev": 72.0,
      "disability": "No",
      "peer": "Positive"
    },
    {
      "id": 34,
      "gender": "Female",
      "school": "Private",
      "score": 59.0,
      "attend": 62.0,
      "hours": 9.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 58.0,
      "disability": "No",
      "peer": "Positive"
    },
    {
      "id": 35,
      "gender": "Male",
      "school": "Public",
      "score": 59.0,
      "attend": 65.0,
      "hours": 6.0,
      "motiv": "Medium",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "No",
      "tutor": 3.0,
      "prev": 62.0,
      "disability": "No",
      "peer": "Neutral"
    },
    {
      "id": 36,
      "gender": "Male",
      "school": "Private",
      "score": 59.0,
      "attend": 60.0,
      "hours": 15.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 91.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 37,
      "gender": "Female",
      "school": "Public",
      "score": 59.0,
      "attend": 64.0,
      "hours": 15.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 59.0,
      "disability": "Yes",
      "peer": "Neutral"
    },
    {
      "id": 38,
      "gender": "Male",
      "school": "Public",
      "score": 61.0,
      "attend": 65.0,
      "hours": 9.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 88.0,
      "disability": "No",
      "peer": "Positive"
    },
    {
      "id": 39,
      "gender": "Male",
      "school": "Public",
      "score": 61.0,
      "attend": 77.0,
      "hours": 9.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 2.0,
      "prev": 57.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 40,
      "gender": "Female",
      "school": "Public",
      "score": 63.0,
      "attend": 67.0,
      "hours": 18.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 2.0,
      "prev": 78.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 41,
      "gender": "Male",
      "school": "Public",
      "score": 60.0,
      "attend": 65.0,
      "hours": 13.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 74.0,
      "disability": "Yes",
      "peer": "Neutral"
    },
    {
      "id": 42,
      "gender": "Male",
      "school": "Public",
      "score": 61.0,
      "attend": 64.0,
      "hours": 15.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 82.0,
      "disability": "No",
      "peer": "Negative"
    },
    {
      "id": 43,
      "gender": "Female",
      "school": "Public",
      "score": 58.0,
      "attend": 61.0,
      "hours": 14.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "No",
      "tutor": 0.0,
      "prev": 82.0,
      "disability": "No",
      "peer": "Neutral"
    },
    {
      "id": 44,
      "gender": "Male",
      "school": "Public",
      "score": 60.0,
      "attend": 67.0,
      "hours": 14.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 68.0,
      "disability": "Yes",
      "peer": "Neutral"
    },
    {
      "id": 45,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 62.0,
      "hours": 13.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 56.0,
      "disability": "Yes",
      "peer": "Positive"
    },
    {
      "id": 46,
      "gender": "Female",
      "school": "Public",
      "score": 61.0,
      "attend": 65.0,
      "hours": 19.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 57.0,
      "disability": "Yes",
      "peer": "Positive"
    },
    {
      "id": 47,
      "gender": "Female",
      "school": "Public",
      "score": 62.0,
      "attend": 75.0,
      "hours": 15.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "No",
      "tutor": 1.0,
      "prev": 94.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 48,
      "gender": "Male",
      "school": "Public",
      "score": 57.0,
      "attend": 66.0,
      "hours": 7.0,
      "motiv": "High",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 0.0,
      "prev": 68.0,
      "disability": "Yes",
      "peer": "Negative"
    },
    {
      "id": 49,
      "gender": "Female",
      "school": "Public",
      "score": 60.0,
      "attend": 66.0,
      "hours": 4.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 4,
      "internet": "Yes",
      "tutor": 2.0,
      "prev": 84.0,
      "disability": "No",
      "peer": "Neutral"
    },
    {
      "id": 50,
      "gender": "Male",
      "school": "Private",
      "score": 58.0,
      "attend": 67.0,
      "hours": 2.0,
      "motiv": "Low",
      "risk": "High",
      "risk_score": 7,
      "persona": 3,
      "internet": "Yes",
      "tutor": 1.0,
      "prev": 73.0,
      "disability": "No",
      "peer": "Positive"
    }
  ],
  "personas": [
    {
      "name": "Driven Achiever",
      "icon": "\ud83d\ude80",
      "color": "#7C3AED",
      "description": "High study hours, excellent attendance, strong motivation. These students consistently perform at the top.",
      "strategies": [
        "Offer advanced challenge projects and enrichment tasks to maintain engagement.",
        "Assign peer mentoring roles to reinforce their own learning through teaching.",
        "Provide access to competitions (Olympiads, subject fairs) and external programs.",
        "Give autonomy in project-based learning \u2014 they thrive with creative freedom.",
        "Regularly celebrate milestones to sustain intrinsic motivation long-term."
      ]
    },
    {
      "name": "Consistent Worker",
      "icon": "\ud83d\udcda",
      "color": "#0EA5E9",
      "description": "Steady attendance and moderate study hours. Reliable performers who respond well to structured learning.",
      "strategies": [
        "Use structured study plans and weekly goal-setting exercises.",
        "Introduce spaced repetition tools (flashcards, quizzes) for retention.",
        "Leverage collaborative study groups \u2014 they excel when paired with peers.",
        "Offer regular, specific feedback to help them identify precise gaps.",
        "Introduce slightly harder problems progressively to build confidence."
      ]
    },
    {
      "name": "Passive Coaster",
      "icon": "\ud83c\udf0a",
      "color": "#F59E0B",
      "description": "Average attendance and minimal study effort. These students coast without clear academic direction.",
      "strategies": [
        "Connect curriculum topics to real-world interests and career relevance.",
        "Use gamified learning (points, leaderboards) to spark engagement.",
        "Check in one-on-one to understand hidden barriers or personal challenges.",
        "Break tasks into short, achievable micro-goals to build momentum.",
        "Introduce choice in assignments to restore a sense of ownership."
      ]
    },
    {
      "name": "Struggling Learner",
      "icon": "\ud83c\udd98",
      "color": "#EF4444",
      "description": "Low attendance, lower previous scores, and limited resources. High risk of falling behind without support.",
      "strategies": [
        "Assign a dedicated mentor or tutor for weekly one-on-one sessions.",
        "Coordinate with parents/guardians to reinforce learning at home.",
        "Use multi-modal teaching (videos, hands-on activities) to suit diverse styles.",
        "Ensure access to school resources: library, devices, tutoring programs.",
        "Create safe, judgment-free classroom environments to reduce anxiety."
      ]
    },
    {
      "name": "Potential Bloomer",
      "icon": "\ud83c\udf31",
      "color": "#10B981",
      "description": "High previous scores but lower current engagement or attendance. Untapped potential waiting to be unlocked.",
      "strategies": [
        "Investigate recent disengagement \u2014 personal, social, or academic triggers.",
        "Reignite curiosity with exploratory, discovery-based learning activities.",
        "Connect them with inspiring role models or alumni in their interest area.",
        "Flexible deadlines and project alternatives reduce pressure triggers.",
        "Offer leadership roles (class rep, project lead) to rebuild confidence."
      ]
    }
  ]
};
